### ISSUE TITLE
Seems a / is missing when uploading logs

### ISSUE THREAD

**Issue by kutzi** [krzysztofslusarski/jvm-gc-logs-analyzer#24]
I tried to upload the log my.log in the webapp. In the log in then see sth. like this:

```
2021-08-03 13:56:43.237 ERROR 18451 --- [nio-8080-exec-4] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception

java.io.FileNotFoundException: /uploads/f118238f-47bb-4690-98b2-cda072a7a1d0my.log (No such file or directory)
	at java.base/java.io.FileOutputStream.open0(Native Method) ~[na:na]
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298) ~[na:na]
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237) ~[na:na]
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:126) ~[na:na]
	at pl.ks.profiling.io.StorageUtils.createCopy(StorageUtils.java:29) ~[io-utils-1.1-SNAPSHOT.jar!/:1.1-SNAPSHOT]
	at pl.ks.profiling.safepoint.analyzer.web.StatsController.enqueue(StatsController.java:82) ~[classes!/:1.1-SNAPSHOT]
```

**Comment by kutzi** [comment]
Same when trying to submit via the HTTP endpoint :-(
`java.io.FileNotFoundException: /uploads/03ab6cb0-299e-46fe-a53a-eb921940de94logs.zip `

**Comment by krzysztofslusarski** [comment]
What OS are you using? Windows?

**Comment by kutzi** [comment]
Linux (CentOS 7)

```
$ java -version
openjdk version "11.0.12" 2021-07-20 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.12+7-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.12+7-LTS, mixed mode, sharing)

```

**Comment by krzysztofslusarski** [comment]
That's really strange, it is mostly tested on Linux :) How do you run an application?

**Comment by kutzi** [comment]
java -jar safepoint-analyzer-web/target/analyzer-web.jar

**Comment by krzysztofslusarski** [comment]
fixed at master

**Comment by kutzi** [comment]
Works now. Great!

**Comment by kutzi** [comment]
Can I ask a different question - because the time in the log file don't seem to match with the ones from the graph?

**Comment by kutzi** [comment]
Great tool BTW.
Thanks a lot for it!

**Comment by krzysztofslusarski** [comment]
Thank you :)

**Comment by krzysztofslusarski** [comment]
"because the time in the log file don't seem to match with the ones from the graph" - for that I would need an example and graph name. There are graphs where I use "gc cycle number" instead of time

**Comment by kutzi** [comment]
> "because the time in the log file don't seem to match with the ones from the graph" - for that I would need an example and graph name. There are graphs where I use "gc cycle number" instead of time

I've deleted the comment, because I simply calculated wrong by one decimal place ;)

One question though: are you accumulating pauses per timeinterval. E.g. if there are 2 G1Concurrent in the same time interval (second?), are the durations of those 2 are being summed up for the graphs or are you trying to render 2 different dots for the in the graph?

**Comment by krzysztofslusarski** [comment]
Most of the time there are 2 dots. Only in:

- Application time (in time) - from safepoint logs
- Allocation rate (in time) - from gc logs

there is aggregation

**Comment by kutzi** [comment]
I think, I've seen it differently. I'll post an example later

**Comment by kutzi** [comment]
Should I use the email address shown in the webapp for further communication? Maybe more appropriate than in an unrelated issue report.

**Comment by krzysztofslusarski** [comment]
pasqal [at] gmail.com
