### ISSUE TITLE
CLI/batch mode

### ISSUE THREAD

**Issue by tkyjovsk** [krzysztofslusarski/jvm-gc-logs-analyzer#32]
It would be great to be able to run this tool via CLI (without GUI) to generate a set of images in some output folder. Maybe as an alternative to the GUI it could also generate an HTML file with the images.

**Comment by krzysztofslusarski** [comment]
I've commited the ```safepoint-analyzer-cli``` module to master branch. If you need prettier HTML / other kind of report fell free to contribute :)
